/*
Script: magnitude_analysis.sql

This script analyzes key measures grouped by different dimensions.
*/

--Find the total customers by countries
select
	country,
	count(distinct customer_id) as total_customers
from gold.dim_customers
group by country
order by count(distinct customer_id) desc;

--Find the total customers by gender
select
	gender,
	count(distinct customer_id) as total_customers
from gold.dim_customers
group by gender
order by case when gender = 'n/a' then 1 else 0 end;

--Find the total products by category
select
	category_name,
	count(distinct product_name) as total_products
from gold.dim_products
group by category_name
order by total_products desc;

--Find the average cost in each category
select
	category_name,
	avg(cost) as avg_cost	
from gold.dim_products
group by category_name
order by avg_cost desc;

--Find the total revenue generated for each category
select
	p.category_name,
	sum(s.sales_amount) as total_revenue
from gold.dim_products p
left join gold.fact_sales s on p.product_key=s.product_key
group by p.category_name
order by total_revenue desc;

--Find the total revenue generated by each customer
select
	c.customer_key,
	c.first_name,
	c.last_name,
	sum(s.sales_amount) as total_revenue
from gold.fact_sales s
left join gold.dim_customers c on s.customer_key=c.customer_key
group by c.customer_key,
					c.first_name,
					c.last_name
order by total_revenue desc;
